# Generated by Django 3.0.6 on 2020-05-24 16:32

from django.db import migrations
from ..models import GROUP_TYPES
from django.contrib.auth.models import Group

def create_group_types(apps, schema_editor):
    for type in GROUP_TYPES:
        Group.objects.create(name=type)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_types)
    ]
