# Generated by Django 3.0.6 on 2020-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200525_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Outstanding',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='paid',
            field=models.IntegerField(null=True),
        ),
    ]
