# Generated by Django 3.0.6 on 2020-05-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_doctor_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='active',
            new_name='status',
        ),
    ]
