# Generated by Django 3.0.6 on 2020-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180404_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
