# Generated by Django 3.0.6 on 2020-05-25 11:05

from django.db import migrations
from ..models import DEFAULT_SELL_PRICE_FOR_CONSULTING, items

def create_consulting_charges(apps, schema_editor):
        items.objects.create(item_name='Consulting Charges', sell_price=DEFAULT_SELL_PRICE_FOR_CONSULTING)

class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200525_1035'),
    ]

    operations = [
        migrations.RunPython(create_consulting_charges)
    ]
